TaskManagement/Controllers/LogInController.cs
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace TaskManagement.Controllers
{
    public class LogInController : Controller
    {
        public UserManager<AppUser> _userManager;
        public RoleManager<AppRole> _roleManager;
        public SignInManager<AppUser> _signInManager;
        public LogInController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }
        public IActionResult LogInUser(string returnUrl)
        {
            TempData["ReturnUrl"] = returnUrl;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LogInUser(UserForLoginDto userForLoginDto)
        {
            if (ModelState.IsValid)
            {
                AppUser user = await _userManager.FindByEmailAsync(userForLoginDto.EMail);
                if (user != null)
                {
                  
                    Microsoft.AspNetCore.Identity.SignInResult result = _signInManager.PasswordSignInAsync(user, userForLoginDto.Password, false, false).Result;
                    IList<string> roles = await _userManager.GetRolesAsync(user);
                    foreach (var item in roles)
                    {

                        if (item.Contains("Yönetici"))
                        {
                            if (TempData["ReturnUrl"] != null)
                            {
                                return Redirect(TempData["ReturnUrl"].ToString());
                            }

                            return RedirectToAction("EmployeeList", "Manager");
                        }
                        else if (item.Contains("Personel"))
                        {
                            if (TempData["ReturnUrl"] != null)
                            {
                                return Redirect(TempData["ReturnUrl"].ToString());
                            }
                            return RedirectToAction("GetTask", "Employee");
                        }
                    }
                    return RedirectToAction("EmployeeList", "Manager");


                }

            }
            else
            {
                ModelState.AddModelError("", "Geçersiz kullanıcı adi veya şifresi");
            }
            return View(userForLoginDto);
        }
    }
}

TaskManagement/Views/LogIn/LogInUser.cshtml
@model UserForLoginDto
@{
    ViewData["Title"] = "LogInUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/Home_root/fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/Home_root/css/owl.carousel.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Home_root/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="~/Home_root/css/style.css">

</head>
<body>
    <div class="content">
        <div class="container">
            <div class="row">
                
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="mb-4">
                                <h3>ÜYE GİRİŞİ</h3>
                                <p class="mb-4">Lütfen Bilgilerinizi Giriniz.</p>
                            </div>
                            <form asp-controller="LogIn" asp-action="LogInUser" method="post">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group first">
                                    <label asp-for="EMail">Mail Adresi</label>
                                    <input asp-for="EMail" class="form-control">
                                    <span asp-validation-for="EMail" class="text-danger"></span>
                                </div>
                                <div class="form-group last mb-4">
                                    <label asp-for="Password">Şifreyi Giriniz</label>
                                    <input asp-for="Password" class="form-control" type="password">
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" asp-action="RememberMe">
                                    <label class="form-check-label" for="flexRadioDefault1">
                                        Beni Hatırla
                                    </label>
                                </div>
           
                                <input type="submit" value="Giriş Yap" class="btn btn-block btn-primary">
                             
                            </form>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>



    <script src="~/Home_root/js/jquery-3.3.1.min.js"></script>
    <script src="~/Home_rootjs/popper.min.js"></script>
    <script src="~/Home_rootjs/bootstrap.min.js"></script>
    <script src="~/Home_rootjs/main.js"></script>
</body>
</html>