TaskManagement/Controllers/EmployeeController.cs
using Business.Abstract;
using Core.Helper;
using DataAccess.Concrete.EntityFramework.Context;
using Entities.Abstract;
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TaskManagement.EnumExtensionsManager;

namespace TaskManagement.Controllers
{
    public class EmployeeController : Controller
    {
        MyContext context = new MyContext();
        public UserManager<AppUser> _userManager;
        public RoleManager<AppRole> _roleManager;
        public SignInManager<AppUser> _signInManager;
        private readonly ITaskProjectService _task;
        private IUserTaskService _userTaskService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public EmployeeController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, SignInManager<AppUser> signInManager, ITaskProjectService task, IUserTaskService userTaskService,IWebHostEnvironment  webHostEnviroment)
        {
            _webHostEnvironment= webHostEnviroment;
            _userTaskService = userTaskService;
            _task = task;
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetTask()
        {
 
      
            List<UserTaskForEmployeeDto> employeeDtos = new List<UserTaskForEmployeeDto>();
            AppUser appUser = _userManager.FindByNameAsync(User.Identity.Name).Result;
            TempData["userId"]=appUser.Id;
            var result = (from ut in _userTaskService.GetList().ToList()
                          join t in _task.GetList().ToList() on ut.TaskId equals t.Id
                          select new
                          {
                              ut.UserId,
                              ut.TaskId,
                              t.Title,
                              t.Id,
                              ut.Status,
                              ut.Priotrity,
                              ut.EndDescription,
                              t.CompletionTime,
                              t.DocumentName



                          }).Where(x=>x.UserId==appUser.Id&&x.TaskId==x.Id);



            foreach (var item in result)
            {
           
                employeeDtos.Add(new UserTaskForEmployeeDto()
                {
                    CompletionTime= item.CompletionTime,
                    Taskİd=item.TaskId,
                    Title= item.Title,
                    Status=item.Status,
                     Priotrity = item.Priotrity,
                     DocumentName=item.DocumentName
                     
                });
               
            }


            return View(employeeDtos);
        }
       public IActionResult ChangeStatus(int enumValue,int taskİd)
        {
            AppUser appUser = _userManager.FindByNameAsync(User.Identity.Name).Result;
            UserTaskDto userTask = new UserTaskDto();
           var result=  _userTaskService.GetByBothId(appUser.Id,taskİd);
            userTask.Id = result.Id;
            userTask.UserId=appUser.Id;
            userTask.TaskId = taskİd;
            userTask.Priotrity = result.Priotrity;
            userTask.ManagerId = result.ManagerId;
            TempData["taskid"] = taskİd;
            //
      
   
            

            if (enumValue==0)
            {
                if (result.Status!= StatusEnums.Wait)
                {
               
                  

                    userTask.Status = StatusEnums.Wait;
                    _userTaskService.Update(userTask);
                  
                }
                return RedirectToAction("GetTask", "Employee");
            }
            else if (enumValue==1)
            {
                if (result.Status!=StatusEnums.Continuing)
                {
             
                    userTask.Status = StatusEnums.Continuing;
                    _userTaskService.Update(userTask);
                
                 

                }
                return RedirectToAction("GetTask", "Employee");
            }
            else
            {
                if (result.Status!=StatusEnums.Completed)
                {
                   


                    userTask.Status = StatusEnums.Completed;
                    _userTaskService.Update(userTask);
                    var manager= _userManager.FindByIdAsync(result.ManagerId).Result;
 
                   CompletedTaskHelper.CompletedTaskEmail(manager.Email);
             
                  
                    return RedirectToAction("CompletedTask", "Employee");
                }
                return RedirectToAction("GetTask", "Employee");
            }

      
        }
        public IActionResult CompletedTask()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CompletedTask(CompletedTaskDto completedTaskDto)
        {
            AppUser appUser = _userManager.FindByNameAsync(User.Identity.Name).Result;
            UserTaskDto userTaskDto = new UserTaskDto();
          
            if (completedTaskDto.DocumentName!=null)
            {
                var extension = Path.GetExtension(completedTaskDto.DocumentName.FileName);
                var newimagename = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/dosyalar/",newimagename);
                var stream = new FileStream(location, FileMode.Create);
                completedTaskDto.DocumentName.CopyTo(stream);
                userTaskDto.DocumentName = newimagename;

            }
            var result = _userTaskService.GetByBothId(appUser.Id, (int)TempData["taskid"]);
            userTaskDto.UserId = appUser.Id;
            userTaskDto.Status=result.Status;
            userTaskDto.Priotrity = result.Priotrity;
            userTaskDto.EndDescription = completedTaskDto.EndDescription;
            userTaskDto.Id = result.Id;

            userTaskDto.TaskId = (int)TempData["taskid"];
            _userTaskService.Update(userTaskDto);





            return View(completedTaskDto);
        }
     

    }
}

TaskManagement/Controllers/LogInController.cs
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace TaskManagement.Controllers
{
    public class LogInController : Controller
    {
        public UserManager<AppUser> _userManager;
        public RoleManager<AppRole> _roleManager;
        public SignInManager<AppUser> _signInManager;
        public LogInController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }
        public IActionResult LogInUser(string returnUrl)
        {
            TempData["ReturnUrl"] = returnUrl;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LogInUser(UserForLoginDto userForLoginDto)
        {
            if (ModelState.IsValid)
            {
                AppUser user = await _userManager.FindByEmailAsync(userForLoginDto.EMail);
                if (user != null)
                {
                  
                    Microsoft.AspNetCore.Identity.SignInResult result = _signInManager.PasswordSignInAsync(user, userForLoginDto.Password, false, false).Result;
                    IList<string> roles = await _userManager.GetRolesAsync(user);
                    foreach (var item in roles)
                    {

                        if (item.Contains("Yönetici"))
                        {
                            if (TempData["ReturnUrl"] != null)
                            {
                                return Redirect(TempData["ReturnUrl"].ToString());
                            }

                            return RedirectToAction("EmployeeList", "Manager");
                        }
                        else if (item.Contains("Personel"))
                        {
                            if (TempData["ReturnUrl"] != null)
                            {
                                return Redirect(TempData["ReturnUrl"].ToString());
                            }
                            return RedirectToAction("GetTask", "Employee");
                        }
                    }
                    return RedirectToAction("EmployeeList", "Manager");


                }

            }
            else
            {
                ModelState.AddModelError("", "Geçersiz kullanıcı adi veya şifresi");
            }
            return View(userForLoginDto);
        }
    }
}

TaskManagement/Controllers/SignUpController.cs
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace TaskManagement.Controllers
{
    public class SignUpController : Controller
    {
   
        public UserManager<AppUser> _userManager;
        public RoleManager<AppRole> _roleManager;

        public SignUpController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
         
        }
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignUp(UserForRegisterDto register)
        {
            AppUser user = new AppUser();
            user.UserName = register.UserName;
            user.FirstName = register.FirstName;
            user.LastName = register.LastName;
            user.Email = register.EMail;
            IdentityResult result = await _userManager.CreateAsync(user,register.Password);
            if (result.Succeeded)
            {
         
                return RedirectToAction("LogInUser", "LogIn");
            }
            else
            {

                ModelState.AddModelError("", "Hata!");
            }
            
            return View(register);

            
        }
        public void AddModelError(IdentityResult result)
        {
            foreach (var item in result.Errors)
            {
                ModelState.AddModelError("", item.Description);
            }
        }
    }
}

TaskManagement/Views/Shared/_Employee.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" >Task Yönetimi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item p-2">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="GetTask">Atanmış Tasklar</a>
                        </li>
                             <li class="nav-item ml-auto p-2">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="LogOut"  asp-route-returnUrl="/LogIn/LogInUser">Çıkış Yap</a>
                        </li>
                      
                  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" >Task Yönetimi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="LogInUser">Giriş Yap</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignUp" asp-action="SignUp">Kayit Ol</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagement/Views/Shared/_Manager.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" >Task Yönetimi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item p-2">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="RoleCreate">Rol Oluştur</a>
                        </li>
                        <li class="nav-item p-2">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="EmployeeList">Personeller</a>
                        </li>
                         <li class="nav-item p-2">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="CreateTask">Task Oluştur</a>
                        </li>
                             <li class="nav-item p-2">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="GetAllTask">Tüm Atanmış Tasklar</a>
                        </li>
                            </li>
                             <li class="nav-item p-2">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="AddEmployee">Personel Ekle</a>
                        </li>
                         
                             <li class="nav-item ml-auto p-2">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="LogOut"  asp-route-returnUrl="/LogIn/LogInUser">Çıkış Yap</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>